### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by aniket23456** [ebhy/budgetml#8]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Stack Trace**
If applicable, add the error stack trace to help explain your problem.

** Context (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Python Version: [e.g. 3.6.6]
 - BudgetML Version: [e.g. 0.1.0]

**Additional information**

**Comment by htahir1** [comment]
@aniket23456 There is no issue started above

**Comment by htahir1** [comment]
@aniket23456 Closing this issue, as there is content in there
